# Generated by Django 5.2.12 on 2026-03-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_collection_id_alter_portfolio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='portfolio_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
