# Generated by Django 5.2.12 on 2026-03-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_collection_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='portfolio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
